spring:
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
